import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Navigation from "./components/navigation"; 
import Footer from "./components/Footer";

import '../lib/fontawesome';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "iCode",
  description: "Generated by create next app",
  icons: {
    icon: "/download.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navigation></Navigation>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
 